// GENERATED by scripts/generate-art-directed-pictures.mjs. Do not edit by hand.
// Run `npm run images:pictures` after changing a crop or adding a photo.

export type PictureVariant = { url: string; w: number };
export type PictureSource = {
  name: string;
  /** <source media>. null = the default crop, used by the <img> itself. */
  media: string | null;
  /** Intrinsic size of the largest variant, for width/height (no layout shift). */
  width: number;
  height: number;
  variants: { avif: PictureVariant[]; webp: PictureVariant[]; jpg: PictureVariant[] };
};

export const ART_DIRECTED_PICTURES = {
  "landing-trainer": {
    "sources": [
      {
        "name": "desktop",
        "media": "(min-width: 768px)",
        "width": 800,
        "height": 1066,
        "variants": {
          "avif": [
            {
              "url": "/images/_pic/landing-trainer-desktop-480.avif",
              "w": 480
            },
            {
              "url": "/images/_pic/landing-trainer-desktop-640.avif",
              "w": 640
            },
            {
              "url": "/images/_pic/landing-trainer-desktop-800.avif",
              "w": 800
            }
          ],
          "webp": [
            {
              "url": "/images/_pic/landing-trainer-desktop-480.webp",
              "w": 480
            },
            {
              "url": "/images/_pic/landing-trainer-desktop-640.webp",
              "w": 640
            },
            {
              "url": "/images/_pic/landing-trainer-desktop-800.webp",
              "w": 800
            }
          ],
          "jpg": [
            {
              "url": "/images/_pic/landing-trainer-desktop-480.jpg",
              "w": 480
            },
            {
              "url": "/images/_pic/landing-trainer-desktop-640.jpg",
              "w": 640
            },
            {
              "url": "/images/_pic/landing-trainer-desktop-800.jpg",
              "w": 800
            }
          ]
        }
      },
      {
        "name": "mobile",
        "media": null,
        "width": 1066,
        "height": 1066,
        "variants": {
          "avif": [
            {
              "url": "/images/_pic/landing-trainer-mobile-640.avif",
              "w": 640
            },
            {
              "url": "/images/_pic/landing-trainer-mobile-828.avif",
              "w": 828
            },
            {
              "url": "/images/_pic/landing-trainer-mobile-1066.avif",
              "w": 1066
            }
          ],
          "webp": [
            {
              "url": "/images/_pic/landing-trainer-mobile-640.webp",
              "w": 640
            },
            {
              "url": "/images/_pic/landing-trainer-mobile-828.webp",
              "w": 828
            },
            {
              "url": "/images/_pic/landing-trainer-mobile-1066.webp",
              "w": 1066
            }
          ],
          "jpg": [
            {
              "url": "/images/_pic/landing-trainer-mobile-640.jpg",
              "w": 640
            },
            {
              "url": "/images/_pic/landing-trainer-mobile-828.jpg",
              "w": 828
            },
            {
              "url": "/images/_pic/landing-trainer-mobile-1066.jpg",
              "w": 1066
            }
          ]
        }
      }
    ]
  },
  "landing-client": {
    "sources": [
      {
        "name": "desktop",
        "media": "(min-width: 768px)",
        "width": 1440,
        "height": 1920,
        "variants": {
          "avif": [
            {
              "url": "/images/_pic/landing-client-desktop-480.avif",
              "w": 480
            },
            {
              "url": "/images/_pic/landing-client-desktop-720.avif",
              "w": 720
            },
            {
              "url": "/images/_pic/landing-client-desktop-960.avif",
              "w": 960
            },
            {
              "url": "/images/_pic/landing-client-desktop-1440.avif",
              "w": 1440
            }
          ],
          "webp": [
            {
              "url": "/images/_pic/landing-client-desktop-480.webp",
              "w": 480
            },
            {
              "url": "/images/_pic/landing-client-desktop-720.webp",
              "w": 720
            },
            {
              "url": "/images/_pic/landing-client-desktop-960.webp",
              "w": 960
            },
            {
              "url": "/images/_pic/landing-client-desktop-1440.webp",
              "w": 1440
            }
          ],
          "jpg": [
            {
              "url": "/images/_pic/landing-client-desktop-480.jpg",
              "w": 480
            },
            {
              "url": "/images/_pic/landing-client-desktop-720.jpg",
              "w": 720
            },
            {
              "url": "/images/_pic/landing-client-desktop-960.jpg",
              "w": 960
            },
            {
              "url": "/images/_pic/landing-client-desktop-1440.jpg",
              "w": 1440
            }
          ]
        }
      },
      {
        "name": "mobile",
        "media": null,
        "width": 1080,
        "height": 1080,
        "variants": {
          "avif": [
            {
              "url": "/images/_pic/landing-client-mobile-640.avif",
              "w": 640
            },
            {
              "url": "/images/_pic/landing-client-mobile-828.avif",
              "w": 828
            },
            {
              "url": "/images/_pic/landing-client-mobile-1080.avif",
              "w": 1080
            }
          ],
          "webp": [
            {
              "url": "/images/_pic/landing-client-mobile-640.webp",
              "w": 640
            },
            {
              "url": "/images/_pic/landing-client-mobile-828.webp",
              "w": 828
            },
            {
              "url": "/images/_pic/landing-client-mobile-1080.webp",
              "w": 1080
            }
          ],
          "jpg": [
            {
              "url": "/images/_pic/landing-client-mobile-640.jpg",
              "w": 640
            },
            {
              "url": "/images/_pic/landing-client-mobile-828.jpg",
              "w": 828
            },
            {
              "url": "/images/_pic/landing-client-mobile-1080.jpg",
              "w": 1080
            }
          ]
        }
      }
    ]
  }
} as const satisfies Record<string, { sources: readonly PictureSource[] }>;

export type ArtDirectedPictureId = keyof typeof ART_DIRECTED_PICTURES;
