// AUTO-GENERATED by scripts/generate-image-color-manifest.mjs.
// Do NOT edit by hand. Run `node scripts/generate-image-color-manifest.mjs`
// to regenerate (also runs in prebuild).
//
// Maps each public image path to its dominant (1×1 average) color as
// a #rrggbb hex string. Used as CSS `background-color` on the wrapper
// element behind <Image> so the user sees a meaningful color preview
// (matched to the image) before the actual image fetches.
//
// Why not blur placeholder: see docs/PERF-EXPERIMENTS-2026-05-07.md.
// (TL;DR: SVG feGaussianBlur regressed Lighthouse mobile LCP by 6-9s.)
//
// Generated: 2026-06-01T08:50:20.340Z
// Total entries: 91
// Skipped (unsupported format): 2

export const IMAGE_COLOR_MANIFEST: Record<string, string> = {
  "/images/general/logo-full.png": "#0f0f0f",
  "/images/hero/canal-view.jpg": "#75716b",
  "/images/hero/gym-entrance.jpeg": "#8a8272",
  "/images/hero/homepage-hero.jpg": "#847a6a",
  "/images/hero/squat-rack.jpeg": "#7a6a5a",
  "/images/hero/training-session.jpg": "#75716b",
  "/images/icon-192.png": "#dc530c",
  "/images/icon-512.png": "#db530c",
  "/images/logo-sculptclub.png": "#0f0f0f",
  "/images/logo.png": "#0f0f0f",
  "/images/og-default.jpg": "#898271",
  "/images/studio/IMG_0857.jpeg": "#796f63",
  "/images/studio/IMG_0858.jpeg": "#83786c",
  "/images/studio/IMG_0859.jpeg": "#806d50",
  "/images/studio/IMG_0861.jpeg": "#776856",
  "/images/studio/IMG_0862.jpeg": "#5b6062",
  "/images/studio/IMG_0864.jpeg": "#8a8272",
  "/images/studio/IMG_0866.jpeg": "#8a7f77",
  "/images/studio/IMG_0867.jpeg": "#635f57",
  "/images/studio/IMG_0868.jpeg": "#6f6859",
  "/images/studio/IMG_0869.jpeg": "#716557",
  "/images/studio/IMG_0871.jpeg": "#6d614c",
  "/images/studio/IMG_0872.jpeg": "#7b776f",
  "/images/studio/IMG_0873.jpeg": "#646260",
  "/images/studio/IMG_0874.jpeg": "#6d665f",
  "/images/studio/IMG_0875.jpeg": "#7a6a5a",
  "/images/studio/IMG_0876.jpeg": "#847f78",
  "/images/studio/IMG_0877.jpeg": "#888173",
  "/images/studio/IMG_0878.jpeg": "#57534f",
  "/images/studio/IMG_0880.jpeg": "#938475",
  "/images/studio/IMG_0881.jpeg": "#888077",
  "/images/studio/IMG_0882.jpeg": "#88796a",
  "/images/studio/IMG_0883.jpeg": "#8e7f6c",
  "/images/studio/IMG_0885.jpeg": "#655d4d",
  "/images/studio/IMG_0886.jpeg": "#5b5141",
  "/images/studio/IMG_0887.jpeg": "#69645b",
  "/images/studio/IMG_0974.jpg": "#7a6d5f",
  "/images/studio/assault-bike.jpeg": "#8e7f6c",
  "/images/studio/back-room-full.jpg": "#69645b",
  "/images/studio/boutique-corner.jpg": "#8e7f6c",
  "/images/studio/canal-view-doors.jpg": "#665d4d",
  "/images/studio/dumbbell-rack.jpeg": "#938475",
  "/images/studio/dumbbells-floor.jpeg": "#888173",
  "/images/studio/echo-bike-corner.jpg": "#88796a",
  "/images/studio/entrance-portrait.jpg": "#94592a",
  "/images/studio/entrance-smile.jpg": "#82481f",
  "/images/studio/entrance.jpeg": "#776856",
  "/images/studio/facade-sculptclub.jpg": "#8a8273",
  "/images/studio/facade.jpeg": "#806d50",
  "/images/studio/gym-latest.jpg": "#7a6d5f",
  "/images/studio/model-facade-full.jpg": "#4d4138",
  "/images/studio/model-facade-relaxed.jpg": "#443b35",
  "/images/studio/portrait-entrance-warm.jpg": "#82451b",
  "/images/studio/power-rack.jpeg": "#888077",
  "/images/studio/pt-session-barbell.jpg": "#56504a",
  "/images/studio/rogue-sled.jpg": "#847f79",
  "/images/studio/sculpt-wall-logo.jpeg": "#57534f",
  "/images/studio/studio-interior-1.jpeg": "#69645b",
  "/images/studio/studio-interior-2.jpeg": "#5b5141",
  "/images/studio/studio-interior-3.jpeg": "#6d665f",
  "/images/studio/studio-overview.jpeg": "#796f63",
  "/images/studio/training-barbell-dramatic.jpg": "#3b2d25",
  "/images/studio/training-barbell-skylight.jpg": "#4f3e35",
  "/images/studio/training-barbell-squat.jpg": "#4d3d36",
  "/images/studio/training-bike-energy.jpg": "#3d1f08",
  "/images/studio/training-bike-smile.jpg": "#2d1706",
  "/images/studio/training-chest-press.jpg": "#582f0b",
  "/images/studio/training-dead-hang.jpg": "#351b07",
  "/images/studio/training-dumbbells-focus.jpg": "#160a06",
  "/images/studio/training-dumbbells-joy.jpg": "#0b0503",
  "/images/studio/training-dumbbells-power.jpg": "#1f1008",
  "/images/studio/training-dumbbells-smile.jpg": "#1a0d06",
  "/images/studio/training-squat-cinematic.jpg": "#2a1c10",
  "/images/studio/turf-lane-canal.jpg": "#5b5141",
  "/images/tiktok-avatar.png": "#db530c",
  "/images/trainers/alex-wp.jpg": "#a69d98",
  "/images/trainers/alex.jpg": "#a69d98",
  "/images/trainers/andrea-wp.jpg": "#8b8075",
  "/images/trainers/andrea.jpg": "#8b8075",
  "/images/trainers/bryan.jpg": "#2f3a30",
  "/images/trainers/dara-wp.jpg": "#868279",
  "/images/trainers/dara.jpg": "#868279",
  "/images/trainers/eva-wp.jpg": "#c9bfbb",
  "/images/trainers/eva.jpg": "#c9bfbb",
  "/images/trainers/gezina.jpg": "#1f1810",
  "/images/trainers/hamish.jpg": "#787271",
  "/images/trainers/ibrahim.jpg": "#595145",
  "/images/trainers/jearmey.jpg": "#635647",
  "/images/trainers/joey-wp.jpg": "#83756b",
  "/images/trainers/joey.jpg": "#6e5c49",
  "/images/trainers/sergei.jpg": "#372922"
};

/** Fallback color for images not in the manifest. Matches site dark theme. */
export const FALLBACK_COLOR = "#0B0907";

/** Get dominant color for an image path. Falls back to dark theme color. */
export function getColor(src: string): string {
  return IMAGE_COLOR_MANIFEST[src] ?? FALLBACK_COLOR;
}
