import { siteConfig } from "@/config/site";
import lastmodRaw from "@/sitemap-lastmod.json";

// Per-route last-modified map. Keys are URL paths (e.g. "/en/blog/foo");
// values are ISO 8601 timestamps generated by scripts/sitemap-lastmod.mjs at
// prebuild from `git log -1 -- <page-file>`. BlogPostingJsonLd uses this to
// emit a fresh `dateModified` whenever the underlying page file is edited —
// without each blog post needing a manual dateModified prop. Per-component
// fallback chain: explicit prop → lastmod map → datePublished.
const lastmodMap = lastmodRaw as Record<string, string>;

// Stable @id refs so other schemas on the page can reference this entity
// without redeclaring fields (@id linking — Aleyda Solis LLM-citation chr #3).
const ORG_ID = `${siteConfig.url}#organization`;
const PLACE_ID = `${siteConfig.url}#localbusiness`;
const WEBSITE_ID = `${siteConfig.url}#website`;

export function LocalBusinessJsonLd() {
  const schema = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Organization",
        "@id": ORG_ID,
        name: siteConfig.name,
        legalName: "SculptClub (P.M. de Vries, eenmanszaak)",
        url: siteConfig.url,
        logo: {
          "@type": "ImageObject",
          url: `${siteConfig.url}/images/logo.png`,
          width: 512,
          height: 512,
        },
        // sameAs expanded from 2 to 3 URLs (added Google Maps verified profile).
        // GEO entity-coherence: AI engines + Knowledge Graph weight Person +
        // Organization + sameAs graphs heavily. More authoritative cross-refs
        // = more citation-ready entity. 2026-05-17 add per @geo audit.
        sameAs: [siteConfig.instagram, siteConfig.tiktok, siteConfig.google],
        // Founder Person sub-entity — establishes Person+Organization
        // entity-coherence pattern AI engines look for. Operator name from
        // llms.txt legal-identity block (P.M. de Vries, eenmanszaak).
        founder: {
          "@type": "Person",
          name: "P.M. de Vries",
          jobTitle: "Founder",
          worksFor: { "@id": ORG_ID },
        },
        foundingDate: siteConfig.founded,
        foundingLocation: {
          "@type": "Place",
          name: "Amsterdam Jordaan",
          address: {
            "@type": "PostalAddress",
            addressLocality: "Amsterdam",
            addressRegion: "Noord-Holland",
            addressCountry: "NL",
          },
        },
        // taxID + identifier add KvK + VAT — official-registry entity signals
        // AI engines weight as credibility (E-E-A-T expertise + authoritativeness).
        identifier: [
          { "@type": "PropertyValue", propertyID: "KvK", value: "64708101" },
          { "@type": "PropertyValue", propertyID: "VAT", value: "NL002250100B57" },
        ],
        contactPoint: {
          "@type": "ContactPoint",
          telephone: siteConfig.phone,
          email: siteConfig.email,
          contactType: "customer service",
          availableLanguage: ["Dutch", "English"],
          areaServed: "NL",
        },
        knowsAbout: [
          "Personal Training",
          "Open Gym",
          "Studio Rental",
          "Strength Training",
          "Boutique Fitness",
          "Amsterdam Jordaan",
        ],
      },
      {
        "@type": "WebSite",
        "@id": WEBSITE_ID,
        url: siteConfig.url,
        name: siteConfig.name,
        publisher: { "@id": ORG_ID },
        inLanguage: ["nl-NL", "en"],
        potentialAction: {
          "@type": "SearchAction",
          target: {
            "@type": "EntryPoint",
            urlTemplate: `${siteConfig.url}/nl/blog?q={search_term_string}`,
          },
          "query-input": "required name=search_term_string",
        },
        // Speakable: voice assistants (Google Assistant, Alexa) and AI Overview
        // spoken-answer extraction prefer pages with explicit speakable hints.
        // Targets H1, H2, and the first paragraph of the main content.
        speakable: {
          "@type": "SpeakableSpecification",
          cssSelector: ["h1", "h2", "main p:first-of-type"],
        },
      },
      {
        "@type": ["LocalBusiness", "HealthClub", "SportsActivityLocation"],
        "@id": PLACE_ID,
        name: siteConfig.name,
        description: siteConfig.description.en,
        url: siteConfig.url,
        telephone: siteConfig.phone,
        email: siteConfig.email,
        parentOrganization: { "@id": ORG_ID },
        address: {
          "@type": "PostalAddress",
          streetAddress: siteConfig.address.street,
          addressLocality: siteConfig.address.city,
          postalCode: siteConfig.address.zip,
          addressCountry: "NL",
          addressRegion: "Noord-Holland",
        },
        geo: {
          "@type": "GeoCoordinates",
          latitude: siteConfig.geo.lat,
          longitude: siteConfig.geo.lng,
        },
        hasMap: siteConfig.google,
        openingHoursSpecification: {
          "@type": "OpeningHoursSpecification",
          dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
          opens: "06:30",
          closes: "22:00",
        },
        aggregateRating: {
          "@type": "AggregateRating",
          ratingValue: siteConfig.rating.value,
          reviewCount: siteConfig.rating.count,
          bestRating: 5,
          worstRating: 1,
        },
        priceRange: "€€",
        paymentAccepted: ["Credit Card", "Apple Pay", "Google Pay"],
        currenciesAccepted: "EUR",
        areaServed: [
          { "@type": "City", name: "Amsterdam" },
          { "@type": "AdministrativeArea", name: "Noord-Holland" },
        ],
        image: [
          `${siteConfig.url}/images/og-default.jpg`,
          `${siteConfig.url}/images/logo-sculptclub.png`,
        ],
        logo: { "@id": `${siteConfig.url}#logo` },
        sameAs: [siteConfig.instagram, siteConfig.tiktok, siteConfig.google],
        foundingDate: siteConfig.founded,
        slogan: "Boutique personal training studio in Amsterdam Jordaan",
        knowsLanguage: ["nl", "en"],
        hasOfferCatalog: {
          "@type": "OfferCatalog",
          name: "SculptClub Services",
          itemListElement: [
            {
              "@type": "OfferCatalog",
              name: "Personal Training",
              itemListElement: [
                {
                  "@type": "Offer",
                  itemOffered: { "@type": "Service", name: "Personal Training Session" },
                  price: 45,
                  priceCurrency: "EUR",
                  description: "1-on-1 personal training, trainers set own rates from €45. Free intro session.",
                },
              ],
            },
            {
              "@type": "OfferCatalog",
              name: "Open Gym",
              itemListElement: [
                { "@type": "Offer", itemOffered: { "@type": "Service", name: "Instapplan — 4 sessions/4 weeks" }, price: 29, priceCurrency: "EUR" },
                { "@type": "Offer", itemOffered: { "@type": "Service", name: "Populair — 8 sessions/4 weeks" }, price: 49, priceCurrency: "EUR" },
                { "@type": "Offer", itemOffered: { "@type": "Service", name: "Intensief — 12 sessions/4 weeks" }, price: 69, priceCurrency: "EUR" },
                { "@type": "Offer", itemOffered: { "@type": "Service", name: "Onbeperkt — unlimited/4 weeks" }, price: 89, priceCurrency: "EUR" },
              ],
            },
            {
              "@type": "OfferCatalog",
              name: "Studio Rental",
              itemListElement: [
                { "@type": "Offer", itemOffered: { "@type": "Service", name: "Half Studio — 60 min" }, price: 12, priceCurrency: "EUR" },
                { "@type": "Offer", itemOffered: { "@type": "Service", name: "Half Studio — 90 min" }, price: 17, priceCurrency: "EUR" },
                { "@type": "Offer", itemOffered: { "@type": "Service", name: "Full Studio — 60 min" }, price: 17, priceCurrency: "EUR" },
                { "@type": "Offer", itemOffered: { "@type": "Service", name: "Full Studio — 90 min" }, price: 24, priceCurrency: "EUR" },
              ],
            },
          ],
        },
      },
    ],
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

export function FaqJsonLd({ faqs }: { faqs: { question: string; answer: string }[] }) {
  const schema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((faq) => ({
      "@type": "Question",
      name: faq.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: faq.answer,
      },
    })),
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

export function ReviewsJsonLd({
  reviews,
}: {
  reviews: {
    name: string;
    text: string;
    rating: number;
    date: string;
  }[];
}) {
  const schema = {
    "@context": "https://schema.org",
    "@type": "LocalBusiness",
    name: siteConfig.name,
    url: siteConfig.url,
    aggregateRating: {
      "@type": "AggregateRating",
      ratingValue: siteConfig.rating.value,
      reviewCount: siteConfig.rating.count,
      bestRating: 5,
    },
    review: reviews.map((r) => ({
      "@type": "Review",
      author: {
        "@type": "Person",
        name: r.name,
      },
      reviewRating: {
        "@type": "Rating",
        ratingValue: r.rating,
        bestRating: 5,
      },
      reviewBody: r.text,
      datePublished: r.date,
    })),
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

export function PersonJsonLd({
  name,
  description,
  image,
  url,
  jobTitle,
  languages,
  sameAs,
}: {
  name: string;
  description: string;
  image: string;
  url: string;
  jobTitle: string;
  languages: string[];
  sameAs?: string[];
}) {
  const schema = {
    "@context": "https://schema.org",
    "@type": "Person",
    name,
    jobTitle,
    description,
    image: image.startsWith("http") ? image : `${siteConfig.url}${image}`,
    url: url.startsWith("http") ? url : `${siteConfig.url}${url}`,
    worksFor: {
      "@type": ["LocalBusiness", "HealthClub"],
      name: siteConfig.name,
      url: siteConfig.url,
      address: {
        "@type": "PostalAddress",
        streetAddress: siteConfig.address.street,
        addressLocality: siteConfig.address.city,
        postalCode: siteConfig.address.zip,
        addressCountry: "NL",
      },
    },
    knowsLanguage: languages.map((l) =>
      l === "NL" ? "Dutch" : l === "EN" ? "English" : l === "PT" ? "Portuguese" : l
    ),
    ...(sameAs && sameAs.length > 0 ? { sameAs } : {}),
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

export function BreadcrumbJsonLd({ items }: { items: { name: string; url: string }[] }) {
  const schema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: `${siteConfig.url}${item.url}`,
    })),
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

export function BlogPostingJsonLd({
  title,
  description,
  url,
  datePublished,
  dateModified,
  wordCount,
  image,
}: {
  title: string;
  description: string;
  url: string;
  datePublished: string;
  dateModified?: string;
  wordCount?: number;
  image?: string;
}) {
  // Resolution chain for dateModified:
  //   1. explicit prop (per-post override, e.g. for backdated republishes)
  //   2. git-commit time from sitemap-lastmod.json (auto-fresh)
  //   3. datePublished (cold-start fallback for posts with no commits since publish)
  const resolvedDateModified =
    dateModified || lastmodMap[url] || datePublished;

  const schema = {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    headline: title,
    description,
    url: `${siteConfig.url}${url}`,
    datePublished,
    dateModified: resolvedDateModified,
    inLanguage: url.startsWith("/en") ? "en-US" : "nl-NL",
    ...(wordCount ? { wordCount } : {}),
    ...(image ? { image: image.startsWith("http") ? image : `${siteConfig.url}${image}` } : {}),
    author: {
      "@type": "Organization",
      name: siteConfig.name,
      url: siteConfig.url,
    },
    publisher: {
      "@type": "Organization",
      name: siteConfig.name,
      url: siteConfig.url,
      logo: {
        "@type": "ImageObject",
        url: `${siteConfig.url}/images/logo.png`,
      },
    },
    mainEntityOfPage: {
      "@type": "WebPage",
      "@id": `${siteConfig.url}${url}`,
    },
    speakable: {
      "@type": "SpeakableSpecification",
      cssSelector: ["h1", "h2", "article p"],
    },
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

export function OfferCatalogJsonLd({
  catalogName,
  description,
  url,
  recurring,
  offers,
}: {
  catalogName: string;
  description: string;
  url: string;
  recurring?: boolean;
  offers: {
    name: string;
    description: string;
    price: number;
    priceCurrency?: string;
    url?: string;
  }[];
}) {
  const schema = {
    "@context": "https://schema.org",
    "@type": "OfferCatalog",
    "@id": `${siteConfig.url}${url}#${catalogName.toLowerCase().replace(/\s+/g, "-")}`,
    name: catalogName,
    description,
    url: `${siteConfig.url}${url}`,
    itemListElement: offers.map((offer) => ({
      "@type": "Offer",
      name: offer.name,
      description: offer.description,
      price: offer.price,
      priceCurrency: offer.priceCurrency || "EUR",
      ...(recurring
        ? { eligibleDuration: { "@type": "QuantitativeValue", value: 4, unitCode: "WEE" } }
        : {}),
      ...(offer.url ? { url: `${siteConfig.url}${offer.url}` } : {}),
      seller: {
        "@type": "LocalBusiness",
        name: siteConfig.name,
      },
    })),
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

/**
 * HowTo schema — high-AEO leverage for "How to ..." queries.
 *
 * AI engines (ChatGPT, Claude, Perplexity, Google SGE) extract HowTo
 * markup and cite it verbatim when answering procedural questions like
 * "how do I book a personal trainer in Amsterdam Jordaan". When the
 * answer comes from our schema, the citation routes traffic to us.
 *
 * 2026-05-17 add — per `/acepilot brain seo geo aeo fastest human user
 * growth` directive. Compounds across every page that embeds it.
 *
 * Usage: pass a name (the "How to X" phrase), description, optional
 * totalTime (ISO 8601 duration like "PT5M"), and steps[] each with
 * name + text + optional url.
 */
export function HowToJsonLd({
  name,
  description,
  totalTime,
  steps,
  image,
}: {
  name: string;
  description: string;
  totalTime?: string; // ISO 8601 duration, e.g. "PT5M" for 5 minutes
  steps: { name: string; text: string; url?: string; image?: string }[];
  image?: string;
}) {
  const schema = {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name,
    description,
    ...(image ? { image: image.startsWith("http") ? image : `${siteConfig.url}${image}` } : {}),
    ...(totalTime ? { totalTime } : {}),
    step: steps.map((s, i) => ({
      "@type": "HowToStep",
      position: i + 1,
      name: s.name,
      text: s.text,
      ...(s.url ? { url: s.url.startsWith("http") ? s.url : `${siteConfig.url}${s.url}` } : {}),
      ...(s.image ? { image: s.image.startsWith("http") ? s.image : `${siteConfig.url}${s.image}` } : {}),
    })),
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

/**
 * DefinedTerm schema — high-GEO leverage for definitional queries.
 *
 * AI engines + Google Knowledge Graph weight DefinedTerm markup highly
 * when extracting definitions. Pages defining domain terms ("Open Gym",
 * "Personal Training", "Calisthenics", "Privé studio") with explicit
 * DefinedTerm schema get cited as authoritative source for "what is X
 * in Amsterdam"-class queries.
 *
 * 2026-05-17 add — per `/acepilot brain seo geo aeo` directive. The
 * inDefinedTermSet anchor lets the brain's own glossary become the
 * authoritative entity reference.
 */
export function DefinedTermJsonLd({
  terms,
  termSetName,
  termSetUrl,
}: {
  terms: { name: string; description: string; url?: string }[];
  termSetName: string;
  termSetUrl?: string;
}) {
  const schema = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "DefinedTermSet",
        "@id": `${siteConfig.url}${termSetUrl || "/glossary"}#termset`,
        name: termSetName,
        ...(termSetUrl ? { url: `${siteConfig.url}${termSetUrl}` } : {}),
        hasDefinedTerm: terms.map((t) => ({
          "@type": "DefinedTerm",
          name: t.name,
          description: t.description,
          ...(t.url ? { url: t.url.startsWith("http") ? t.url : `${siteConfig.url}${t.url}` } : {}),
          inDefinedTermSet: `${siteConfig.url}${termSetUrl || "/glossary"}#termset`,
        })),
      },
    ],
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

export function ServiceJsonLd({
  name,
  description,
  url,
  priceRange,
  areaServed,
}: {
  name: string;
  description: string;
  url: string;
  priceRange: string;
  areaServed?: string;
}) {
  const schema = {
    "@context": "https://schema.org",
    "@type": "Service",
    name,
    description,
    url: `${siteConfig.url}${url}`,
    provider: {
      "@type": "LocalBusiness",
      name: siteConfig.name,
      url: siteConfig.url,
      address: {
        "@type": "PostalAddress",
        streetAddress: siteConfig.address.street,
        addressLocality: siteConfig.address.city,
        postalCode: siteConfig.address.zip,
        addressCountry: "NL",
      },
    },
    areaServed: {
      "@type": "City",
      name: areaServed || "Amsterdam",
    },
    priceRange,
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}
