export type BlogPost = {
  slug: string;
  locale: "nl" | "en";
  title: string;
  description: string;
  tags: string[];
  publishedAt: string; // YYYY-MM-DD
  href: string;
};

// Blog registry — every NL and EN blog post on sculptclub.nl.
// Used by src/lib/related-posts.ts to drive the RelatedPosts module.
export const blogPosts: BlogPost[] = [
  // ---------- NL ----------
  {
    slug: "afvallen-met-krachttraining",
    locale: "nl",
    title: "Afvallen met krachttraining",
    description: "Waarom krachttraining werkt voor gewichtsverlies.",
    tags: ["weight-loss", "beginners"],
    publishedAt: "2026-03-24",
    href: "/nl/blog/afvallen-met-krachttraining",
  },
  {
    slug: "boutique-gym-vs-sportschool-keten",
    locale: "nl",
    title: "Boutique gym vs sportschool keten",
    description: "Wat past bij jou: klein en persoonlijk of groot en anoniem?",
    tags: ["comparison"],
    publishedAt: "2026-04-02",
    href: "/nl/blog/boutique-gym-vs-sportschool-keten",
  },
  {
    slug: "consistent-blijven-met-sporten",
    locale: "nl",
    title: "Hoe blijf je consistent met sporten?",
    description: "7 bewezen tips om vol te houden.",
    tags: ["beginners"],
    publishedAt: "2026-03-26",
    href: "/nl/blog/consistent-blijven-met-sporten",
  },
  {
    slug: "eerste-keer-sportschool-tips",
    locale: "nl",
    title: "Eerste keer naar de sportschool",
    description: "7 tips voor beginners.",
    tags: ["beginners"],
    publishedAt: "2026-03-24",
    href: "/nl/blog/eerste-keer-sportschool-tips",
  },
  {
    slug: "fysiotherapeut-personal-trainer-amsterdam",
    locale: "nl",
    title: "Fysiotherapeut als personal trainer",
    description: "Trainen met een blessure onder professionele begeleiding.",
    tags: ["physio", "injury"],
    publishedAt: "2026-03-30",
    href: "/nl/blog/fysiotherapeut-personal-trainer-amsterdam",
  },
  {
    slug: "fysiotherapie-studio-huren-amsterdam",
    locale: "nl",
    title: "Fysiotherapie studio huren in Amsterdam",
    description: "Een ruimte voor fysio's in de Jordaan.",
    tags: ["physio", "studio"],
    publishedAt: "2026-04-02",
    href: "/nl/blog/fysiotherapie-studio-huren-amsterdam",
  },
  {
    slug: "gratis-intake-personal-trainer-amsterdam",
    locale: "nl",
    title: "Gratis intake personal trainer",
    description: "Wat te verwachten van je eerste kennismaking.",
    tags: ["intake", "beginners"],
    publishedAt: "2026-04-01",
    href: "/nl/blog/gratis-intake-personal-trainer-amsterdam",
  },
  {
    slug: "gym-huren-per-uur-amsterdam",
    locale: "nl",
    title: "Gym huren per uur in Amsterdam",
    description: "Flexibele trainingsruimte voor ZZP-trainers.",
    tags: ["studio", "become-trainer"],
    publishedAt: "2026-04-01",
    href: "/nl/blog/gym-huren-per-uur-amsterdam",
  },
  {
    slug: "krachttraining-voor-beginners",
    locale: "nl",
    title: "Krachttraining voor beginners",
    description: "Een complete gids om te starten.",
    tags: ["beginners"],
    publishedAt: "2026-03-24",
    href: "/nl/blog/krachttraining-voor-beginners",
  },
  {
    slug: "krachttraining-voor-vrouwen",
    locale: "nl",
    title: "Krachttraining voor vrouwen in Amsterdam",
    description: "Waarom kracht juist voor vrouwen werkt.",
    tags: ["women"],
    publishedAt: "2026-04-03",
    href: "/nl/blog/krachttraining-voor-vrouwen",
  },
  {
    slug: "open-gym-vs-sportschool",
    locale: "nl",
    title: "Open Gym vs sportschool",
    description: "Wat past bij jou?",
    tags: ["open-gym", "comparison"],
    publishedAt: "2026-03-24",
    href: "/nl/blog/open-gym-vs-sportschool",
  },
  {
    slug: "personal-trainer-amsterdam-centrum",
    locale: "nl",
    title: "Personal trainer Amsterdam Centrum",
    description: "Privé training om de hoek van de Dam.",
    tags: ["neighbourhood"],
    publishedAt: "2026-04-02",
    href: "/nl/blog/personal-trainer-amsterdam-centrum",
  },
  {
    slug: "personal-trainer-amsterdam-noord",
    locale: "nl",
    title: "Personal trainer Amsterdam Noord",
    description: "Privé training over het IJ.",
    tags: ["neighbourhood"],
    publishedAt: "2026-04-08",
    href: "/nl/blog/personal-trainer-amsterdam-noord",
  },
  {
    slug: "personal-trainer-amsterdam-oost",
    locale: "nl",
    title: "Personal trainer Amsterdam Oost",
    description: "Privé training op 15 minuten van Oost.",
    tags: ["neighbourhood"],
    publishedAt: "2026-04-02",
    href: "/nl/blog/personal-trainer-amsterdam-oost",
  },
  {
    slug: "personal-trainer-amsterdam-west",
    locale: "nl",
    title: "Personal trainer Amsterdam West",
    description: "Privé training in de Jordaan, om de hoek van West.",
    tags: ["neighbourhood"],
    publishedAt: "2026-04-02",
    href: "/nl/blog/personal-trainer-amsterdam-west",
  },
  {
    slug: "personal-trainer-amsterdam-zuid",
    locale: "nl",
    title: "Personal trainer Amsterdam Zuid",
    description: "SculptClub in de Jordaan voor Zuid-bewoners.",
    tags: ["neighbourhood"],
    publishedAt: "2026-04-03",
    href: "/nl/blog/personal-trainer-amsterdam-zuid",
  },
  {
    slug: "personal-trainer-amsterdam",
    locale: "nl",
    title: "Personal trainer in Amsterdam",
    description: "Zo vind je de beste match.",
    tags: ["generic"],
    publishedAt: "2026-03-24",
    href: "/nl/blog/personal-trainer-amsterdam",
  },
  {
    slug: "personal-trainer-de-pijp-amsterdam",
    locale: "nl",
    title: "Personal trainer De Pijp Amsterdam",
    description: "Privé training voor bewoners van De Pijp.",
    tags: ["neighbourhood"],
    publishedAt: "2026-04-02",
    href: "/nl/blog/personal-trainer-de-pijp-amsterdam",
  },
  {
    slug: "personal-trainer-na-blessure-amsterdam",
    locale: "nl",
    title: "Personal trainer na een blessure",
    description: "Veilig terugkomen na een blessure.",
    tags: ["injury", "physio"],
    publishedAt: "2026-04-03",
    href: "/nl/blog/personal-trainer-na-blessure-amsterdam",
  },
  {
    slug: "personal-trainer-voor-beginners",
    locale: "nl",
    title: "Personal trainer voor beginners",
    description: "Wat je kunt verwachten als je net begint.",
    tags: ["beginners", "intake"],
    publishedAt: "2026-04-02",
    href: "/nl/blog/personal-trainer-voor-beginners",
  },
  {
    slug: "personal-trainer-voor-senioren-amsterdam",
    locale: "nl",
    title: "Personal trainer voor senioren",
    description: "Krachttraining op latere leeftijd.",
    tags: ["seniors"],
    publishedAt: "2026-04-03",
    href: "/nl/blog/personal-trainer-voor-senioren-amsterdam",
  },
  {
    slug: "personal-trainer-worden-amsterdam",
    locale: "nl",
    title: "Personal trainer worden in Amsterdam",
    description: "Zo begin je als zelfstandig trainer.",
    tags: ["become-trainer", "studio"],
    publishedAt: "2026-04-03",
    href: "/nl/blog/personal-trainer-worden-amsterdam",
  },
  {
    slug: "personal-training-afvallen-amsterdam",
    locale: "nl",
    title: "Personal training voor afvallen",
    description: "Trainen voor duurzaam gewichtsverlies.",
    tags: ["weight-loss"],
    publishedAt: "2026-04-02",
    href: "/nl/blog/personal-training-afvallen-amsterdam",
  },
  {
    slug: "personal-training-amsterdam-jordaan",
    locale: "nl",
    title: "Personal training in Amsterdam Jordaan",
    description: "Wat je moet weten over training in de Jordaan.",
    tags: ["jordaan", "neighbourhood"],
    publishedAt: "2026-03-24",
    href: "/nl/blog/personal-training-amsterdam-jordaan",
  },
  {
    slug: "prive-sportschool-vs-grote-sportschool",
    locale: "nl",
    title: "Privé sportschool vs grote sportschool",
    description: "De belangrijkste verschillen op een rij.",
    tags: ["comparison"],
    publishedAt: "2026-03-26",
    href: "/nl/blog/prive-sportschool-vs-grote-sportschool",
  },
  {
    slug: "sportschool-jordaan-amsterdam",
    locale: "nl",
    title: "Sportschool Jordaan Amsterdam",
    description: "Jouw opties in de Jordaan op een rij.",
    tags: ["jordaan", "neighbourhood"],
    publishedAt: "2026-04-02",
    href: "/nl/blog/sportschool-jordaan-amsterdam",
  },
  {
    slug: "sportschool-zonder-abonnement-amsterdam",
    locale: "nl",
    title: "Sportschool zonder abonnement",
    description: "Je opties zonder contract.",
    tags: ["open-gym", "cost"],
    publishedAt: "2026-03-24",
    href: "/nl/blog/sportschool-zonder-abonnement-amsterdam",
  },
  {
    slug: "studio-huren-personal-trainer-amsterdam",
    locale: "nl",
    title: "Studio huren als personal trainer",
    description: "Een privé studio huren voor je sessies.",
    tags: ["studio", "become-trainer"],
    publishedAt: "2026-03-26",
    href: "/nl/blog/studio-huren-personal-trainer-amsterdam",
  },
  {
    slug: "trainingsruimte-huren-zzp-trainer-amsterdam",
    locale: "nl",
    title: "Trainingsruimte huren als ZZP trainer",
    description: "Flexibele ruimte voor zelfstandige trainers.",
    tags: ["studio", "become-trainer"],
    publishedAt: "2026-04-02",
    href: "/nl/blog/trainingsruimte-huren-zzp-trainer-amsterdam",
  },
  {
    slug: "voedingscoach-amsterdam",
    locale: "nl",
    title: "Voedingscoach Amsterdam",
    description: "Wat doet een diëtist en wanneer heb je er een nodig?",
    tags: ["nutrition"],
    publishedAt: "2026-03-30",
    href: "/nl/blog/voedingscoach-amsterdam",
  },
  {
    slug: "wat-kost-personal-training-amsterdam",
    locale: "nl",
    title: "Wat kost personal training?",
    description: "Prijzen en uitleg op een rij.",
    tags: ["cost"],
    publishedAt: "2026-03-24",
    href: "/nl/blog/wat-kost-personal-training-amsterdam",
  },
  {
    slug: "zakelijk-personal-training-amsterdam",
    locale: "nl",
    title: "Zakelijk personal training Amsterdam",
    description: "Personal training voor teams en bedrijven.",
    tags: ["corporate"],
    publishedAt: "2026-04-08",
    href: "/nl/blog/zakelijk-personal-training-amsterdam",
  },

  // ---------- EN ----------
  {
    slug: "become-personal-trainer-amsterdam",
    locale: "en",
    title: "Become a personal trainer in Amsterdam",
    description: "How to start as a freelance trainer.",
    tags: ["become-trainer", "studio"],
    publishedAt: "2026-04-03",
    href: "/en/blog/become-personal-trainer-amsterdam",
  },
  {
    slug: "boutique-gym-vs-big-chain-gym",
    locale: "en",
    title: "Boutique gym vs big chain gym",
    description: "What's right for you?",
    tags: ["comparison"],
    publishedAt: "2026-04-02",
    href: "/en/blog/boutique-gym-vs-big-chain-gym",
  },
  {
    slug: "corporate-personal-training-amsterdam",
    locale: "en",
    title: "Corporate personal training Amsterdam",
    description: "Training programs for teams and companies.",
    tags: ["corporate"],
    publishedAt: "2026-04-08",
    href: "/en/blog/corporate-personal-training-amsterdam",
  },
  {
    slug: "first-time-gym-tips",
    locale: "en",
    title: "First time at the gym",
    description: "7 tips for beginners.",
    tags: ["beginners"],
    publishedAt: "2026-03-24",
    href: "/en/blog/first-time-gym-tips",
  },
  {
    slug: "free-intro-personal-trainer-amsterdam",
    locale: "en",
    title: "Free intro personal trainer Amsterdam",
    description: "What to expect from your first session.",
    tags: ["intake", "beginners"],
    publishedAt: "2026-04-01",
    href: "/en/blog/free-intro-personal-trainer-amsterdam",
  },
  {
    slug: "gym-jordaan-amsterdam",
    locale: "en",
    title: "Gym in the Jordaan Amsterdam",
    description: "Your options in the Jordaan compared.",
    tags: ["jordaan", "neighbourhood"],
    publishedAt: "2026-04-02",
    href: "/en/blog/gym-jordaan-amsterdam",
  },
  {
    slug: "gym-rental-per-hour-amsterdam",
    locale: "en",
    title: "Gym rental per hour Amsterdam",
    description: "Flexible studio for freelance trainers.",
    tags: ["studio", "become-trainer"],
    publishedAt: "2026-04-01",
    href: "/en/blog/gym-rental-per-hour-amsterdam",
  },
  {
    slug: "gym-without-membership-amsterdam",
    locale: "en",
    title: "Gym without membership in Amsterdam",
    description: "Your options without a contract.",
    tags: ["open-gym", "cost"],
    publishedAt: "2026-03-24",
    href: "/en/blog/gym-without-membership-amsterdam",
  },
  {
    slug: "nutrition-coach-amsterdam",
    locale: "en",
    title: "Nutrition coach Amsterdam",
    description: "Do you need a dietitian for your training?",
    tags: ["nutrition"],
    publishedAt: "2026-03-30",
    href: "/en/blog/nutrition-coach-amsterdam",
  },
  {
    slug: "open-gym-vs-regular-gym",
    locale: "en",
    title: "Open Gym vs regular gym",
    description: "Which is right for you?",
    tags: ["open-gym", "comparison"],
    publishedAt: "2026-03-24",
    href: "/en/blog/open-gym-vs-regular-gym",
  },
  {
    slug: "personal-trainer-after-injury-amsterdam",
    locale: "en",
    title: "Personal trainer after an injury",
    description: "Safely returning to training after an injury.",
    tags: ["injury", "physio"],
    publishedAt: "2026-04-03",
    href: "/en/blog/personal-trainer-after-injury-amsterdam",
  },
  {
    slug: "personal-trainer-amsterdam-centrum",
    locale: "en",
    title: "Personal trainer Amsterdam Centrum",
    description: "Private training around the corner from Dam Square.",
    tags: ["neighbourhood"],
    publishedAt: "2026-04-02",
    href: "/en/blog/personal-trainer-amsterdam-centrum",
  },
  {
    slug: "personal-trainer-amsterdam-east",
    locale: "en",
    title: "Personal trainer Amsterdam East",
    description: "Private training a short ride from East.",
    tags: ["neighbourhood"],
    publishedAt: "2026-04-02",
    href: "/en/blog/personal-trainer-amsterdam-east",
  },
  {
    slug: "personal-trainer-amsterdam-north",
    locale: "en",
    title: "Personal trainer Amsterdam North",
    description: "Private training across the IJ.",
    tags: ["neighbourhood"],
    publishedAt: "2026-04-08",
    href: "/en/blog/personal-trainer-amsterdam-north",
  },
  {
    slug: "personal-trainer-amsterdam-south",
    locale: "en",
    title: "Personal trainer Amsterdam South",
    description: "SculptClub in the Jordaan for residents of South.",
    tags: ["neighbourhood"],
    publishedAt: "2026-04-03",
    href: "/en/blog/personal-trainer-amsterdam-south",
  },
  {
    slug: "personal-trainer-amsterdam-west",
    locale: "en",
    title: "Personal trainer Amsterdam West",
    description: "Private training in the Jordaan, next to West.",
    tags: ["neighbourhood"],
    publishedAt: "2026-04-02",
    href: "/en/blog/personal-trainer-amsterdam-west",
  },
  {
    slug: "personal-trainer-amsterdam",
    locale: "en",
    title: "Personal trainer in Amsterdam",
    description: "How to find the best match.",
    tags: ["generic"],
    publishedAt: "2026-03-24",
    href: "/en/blog/personal-trainer-amsterdam",
  },
  {
    slug: "personal-trainer-de-pijp-amsterdam",
    locale: "en",
    title: "Personal trainer De Pijp Amsterdam",
    description: "Private training for De Pijp residents.",
    tags: ["neighbourhood"],
    publishedAt: "2026-04-02",
    href: "/en/blog/personal-trainer-de-pijp-amsterdam",
  },
  {
    slug: "personal-trainer-for-beginners",
    locale: "en",
    title: "Personal trainer for beginners",
    description: "What to expect when you're just starting.",
    tags: ["beginners", "intake"],
    publishedAt: "2026-04-02",
    href: "/en/blog/personal-trainer-for-beginners",
  },
  {
    slug: "personal-trainer-for-seniors-amsterdam",
    locale: "en",
    title: "Personal trainer for seniors",
    description: "Strength training in later life.",
    tags: ["seniors"],
    publishedAt: "2026-04-03",
    href: "/en/blog/personal-trainer-for-seniors-amsterdam",
  },
  {
    slug: "personal-training-amsterdam-jordaan",
    locale: "en",
    title: "Personal training in Amsterdam Jordaan",
    description: "What to know about training in the Jordaan.",
    tags: ["jordaan", "neighbourhood"],
    publishedAt: "2026-03-24",
    href: "/en/blog/personal-training-amsterdam-jordaan",
  },
  {
    slug: "personal-training-cost-amsterdam",
    locale: "en",
    title: "How much does personal training cost?",
    description: "Prices and explanation.",
    tags: ["cost"],
    publishedAt: "2026-03-24",
    href: "/en/blog/personal-training-cost-amsterdam",
  },
  {
    slug: "personal-training-weight-loss-amsterdam",
    locale: "en",
    title: "Personal training for weight loss",
    description: "Training for sustainable weight loss.",
    tags: ["weight-loss"],
    publishedAt: "2026-04-02",
    href: "/en/blog/personal-training-weight-loss-amsterdam",
  },
  {
    slug: "physiotherapist-personal-trainer-amsterdam",
    locale: "en",
    title: "Physiotherapist as personal trainer",
    description: "Training with an injury under professional guidance.",
    tags: ["physio", "injury"],
    publishedAt: "2026-03-30",
    href: "/en/blog/physiotherapist-personal-trainer-amsterdam",
  },
  {
    slug: "physiotherapy-studio-rental-amsterdam",
    locale: "en",
    title: "Physiotherapy studio rental Amsterdam",
    description: "A space for physios in the Jordaan.",
    tags: ["physio", "studio"],
    publishedAt: "2026-04-02",
    href: "/en/blog/physiotherapy-studio-rental-amsterdam",
  },
  {
    slug: "private-gym-vs-big-box-gym",
    locale: "en",
    title: "Private gym vs big box gym",
    description: "The key differences.",
    tags: ["comparison"],
    publishedAt: "2026-03-26",
    href: "/en/blog/private-gym-vs-big-box-gym",
  },
  {
    slug: "rent-training-space-freelance-personal-trainer-amsterdam",
    locale: "en",
    title: "Rent training space as a freelance trainer",
    description: "Flexible space for independent trainers.",
    tags: ["studio", "become-trainer"],
    publishedAt: "2026-04-02",
    href: "/en/blog/rent-training-space-freelance-personal-trainer-amsterdam",
  },
  {
    slug: "stay-consistent-exercise",
    locale: "en",
    title: "How to stay consistent with exercise",
    description: "7 proven tips that stick.",
    tags: ["beginners"],
    publishedAt: "2026-03-26",
    href: "/en/blog/stay-consistent-exercise",
  },
  {
    slug: "strength-training-beginners-guide",
    locale: "en",
    title: "Strength training for beginners",
    description: "A complete guide to getting started.",
    tags: ["beginners"],
    publishedAt: "2026-03-24",
    href: "/en/blog/strength-training-beginners-guide",
  },
  {
    slug: "strength-training-for-women",
    locale: "en",
    title: "Strength training for women",
    description: "Why strength training works for women.",
    tags: ["women"],
    publishedAt: "2026-04-03",
    href: "/en/blog/strength-training-for-women",
  },
  {
    slug: "studio-rental-personal-trainers-amsterdam",
    locale: "en",
    title: "Studio rental for personal trainers",
    description: "Rent a private studio for your sessions.",
    tags: ["studio", "become-trainer"],
    publishedAt: "2026-03-26",
    href: "/en/blog/studio-rental-personal-trainers-amsterdam",
  },
  {
    slug: "weight-loss-strength-training",
    locale: "en",
    title: "Weight loss through strength training",
    description: "Why it works.",
    tags: ["weight-loss", "beginners"],
    publishedAt: "2026-03-24",
    href: "/en/blog/weight-loss-strength-training",
  },
];
